import type { TaskType, ModelProfile } from "./types.js";

// Static affinity scores: how well each model fits each task type (0-1)
// Used for cold-start routing before performance history builds up
export const DEFAULT_AFFINITIES: Record<TaskType, Record<string, number>> = {
  coding: {
    "claude-opus-4-6": 0.95,
    "claude-sonnet-4-6": 0.90,
    "deepseek-r1": 0.92,
    "deepseek-v3": 0.85,
    "gpt-4o": 0.82,
    "grok-3": 0.80,
    "grok-3-mini": 0.75,
    "mistral-large-latest": 0.78,
    "codestral-latest": 0.88,
    "gemini-2.5-flash": 0.70,
    "kimi-k2-thinking": 0.72,
    "llama-3.3-70b": 0.74,
    "command-r-plus": 0.68,
    "glm-5.1": 0.65,
    "glm-5": 0.60,
  },
  research: {
    "sonar-pro": 0.95,
    "sonar": 0.85,
    "grok-3": 0.85,
    "gemini-2.5-flash": 0.80,
    "kimi-k2.5": 0.75,
    "command-r-plus": 0.78,
    "gpt-4o": 0.72,
    "claude-sonnet-4-6": 0.70,
    "mistral-large-latest": 0.68,
    "deepseek-v3": 0.65,
    "glm-5.1": 0.60,
  },
  creative_writing: {
    "claude-sonnet-4-6": 0.90,
    "claude-opus-4-6": 0.88,
    "gpt-4o": 0.85,
    "grok-3": 0.82,
    "mistral-large-latest": 0.78,
    "command-r-plus": 0.75,
    "gemini-2.5-flash": 0.70,
    "kimi-k2.5": 0.68,
    "deepseek-v3": 0.65,
    "glm-5.1": 0.60,
  },
  analysis: {
    "claude-opus-4-6": 0.92,
    "deepseek-r1": 0.90,
    "claude-sonnet-4-6": 0.85,
    "kimi-k2-thinking": 0.85,
    "grok-3": 0.83,
    "gpt-4o": 0.80,
    "mistral-large-latest": 0.78,
    "command-r-plus": 0.76,
    "gemini-2.5-flash": 0.75,
    "deepseek-v3": 0.72,
    "glm-5.1": 0.70,
  },
  image_gen: {
    "dall-e-3": 0.90,
    "imagen-3": 0.88,
    "grok-2-image": 0.85,
  },
  translation: {
    "gpt-4o": 0.88,
    "claude-sonnet-4-6": 0.85,
    "mistral-large-latest": 0.84,
    "gemini-2.5-flash": 0.82,
    "command-r-plus": 0.80,
    "grok-3": 0.78,
    "deepseek-v3": 0.76,
    "glm-5": 0.75,
    "kimi-k2.5": 0.72,
  },
  summarization: {
    "gemini-2.5-flash": 0.90,
    "claude-sonnet-4-6": 0.85,
    "command-r-plus": 0.83,
    "grok-3-mini": 0.82,
    "gpt-4o": 0.80,
    "mistral-large-latest": 0.78,
    "glm-5.1": 0.78,
    "deepseek-v3": 0.76,
    "kimi-k2.5": 0.75,
    "llama-3.3-70b": 0.72,
  },
  data_extraction: {
    "gemini-2.5-flash": 0.88,
    "gpt-4o": 0.85,
    "claude-sonnet-4-6": 0.82,
    "deepseek-v3": 0.78,
    "mistral-large-latest": 0.76,
    "grok-3-mini": 0.74,
    "command-r-plus": 0.72,
    "glm-4.7": 0.70,
    "kimi-k2.5": 0.68,
  },
  math_reasoning: {
    "claude-opus-4-6": 0.92,
    "deepseek-r1": 0.93,
    "kimi-k2-thinking": 0.90,
    "grok-3": 0.85,
    "gpt-4o": 0.82,
    "mistral-large-latest": 0.78,
    "glm-5.1": 0.78,
    "gemini-2.5-flash": 0.72,
    "deepseek-v3": 0.70,
  },
};

export const MODEL_PROFILES: ModelProfile[] = [
  // Anthropic
  {
    provider: "anthropic",
    model: "claude-opus-4-6",
    capabilities: ["coding", "analysis", "creative_writing", "math_reasoning", "summarization", "data_extraction", "translation", "research"],
    contextWindow: 200000,
    costPer1kInput: 1.5,
    costPer1kOutput: 7.5,
    tier: "premium",
  },
  {
    provider: "anthropic",
    model: "claude-sonnet-4-6",
    capabilities: ["coding", "analysis", "creative_writing", "math_reasoning", "summarization", "data_extraction", "translation", "research"],
    contextWindow: 200000,
    costPer1kInput: 0.3,
    costPer1kOutput: 1.5,
    tier: "standard",
  },
  // OpenAI
  {
    provider: "openai",
    model: "gpt-4o",
    capabilities: ["coding", "analysis", "creative_writing", "math_reasoning", "summarization", "data_extraction", "translation", "research"],
    contextWindow: 128000,
    costPer1kInput: 0.25,
    costPer1kOutput: 1.0,
    tier: "standard",
  },
  {
    provider: "openai",
    model: "dall-e-3",
    capabilities: ["image_gen"],
    contextWindow: 4000,
    costPer1kInput: 0,
    costPer1kOutput: 0,
    tier: "standard",
  },
  // Google Gemini
  {
    provider: "gemini",
    model: "gemini-2.5-flash",
    capabilities: ["coding", "analysis", "creative_writing", "summarization", "data_extraction", "translation", "research", "math_reasoning"],
    contextWindow: 1000000,
    costPer1kInput: 0.015,
    costPer1kOutput: 0.06,
    tier: "budget",
  },
  // Perplexity
  {
    provider: "perplexity",
    model: "sonar-pro",
    capabilities: ["research"],
    contextWindow: 200000,
    costPer1kInput: 0.3,
    costPer1kOutput: 1.5,
    tier: "standard",
  },
  {
    provider: "perplexity",
    model: "sonar",
    capabilities: ["research"],
    contextWindow: 128000,
    costPer1kInput: 0.1,
    costPer1kOutput: 0.1,
    tier: "budget",
  },
  // Moonshot / Kimi
  {
    provider: "moonshot",
    model: "kimi-k2.5",
    capabilities: ["coding", "analysis", "creative_writing", "summarization", "data_extraction", "translation", "research", "math_reasoning"],
    contextWindow: 262000,
    costPer1kInput: 0.1,
    costPer1kOutput: 0.3,
    tier: "budget",
  },
  {
    provider: "moonshot",
    model: "kimi-k2-thinking",
    capabilities: ["coding", "analysis", "math_reasoning", "data_extraction"],
    contextWindow: 262000,
    costPer1kInput: 0.1,
    costPer1kOutput: 0.3,
    tier: "budget",
  },
  // Z.AI / GLM
  {
    provider: "zai",
    model: "glm-5.1",
    capabilities: ["coding", "analysis", "creative_writing", "summarization", "data_extraction", "translation", "math_reasoning"],
    contextWindow: 202000,
    costPer1kInput: 0.12,
    costPer1kOutput: 0.4,
    tier: "budget",
  },
  {
    provider: "zai",
    model: "glm-5",
    capabilities: ["coding", "analysis", "creative_writing", "summarization", "data_extraction", "translation", "math_reasoning"],
    contextWindow: 202000,
    costPer1kInput: 0.1,
    costPer1kOutput: 0.32,
    tier: "budget",
  },
  {
    provider: "zai",
    model: "glm-4.7",
    capabilities: ["coding", "analysis", "summarization", "data_extraction", "translation"],
    contextWindow: 128000,
    costPer1kInput: 0.05,
    costPer1kOutput: 0.15,
    tier: "budget",
  },
  // xAI / Grok
  {
    provider: "grok",
    model: "grok-3",
    capabilities: ["coding", "analysis", "creative_writing", "math_reasoning", "summarization", "data_extraction", "translation", "research"],
    contextWindow: 131072,
    costPer1kInput: 0.3,
    costPer1kOutput: 0.5,
    tier: "standard",
  },
  {
    provider: "grok",
    model: "grok-3-mini",
    capabilities: ["coding", "analysis", "summarization", "data_extraction", "math_reasoning"],
    contextWindow: 131072,
    costPer1kInput: 0.1,
    costPer1kOutput: 0.2,
    tier: "budget",
  },
  // DeepSeek
  {
    provider: "deepseek",
    model: "deepseek-r1",
    capabilities: ["coding", "analysis", "math_reasoning", "data_extraction"],
    contextWindow: 128000,
    costPer1kInput: 0.055,
    costPer1kOutput: 0.22,
    tier: "budget",
  },
  {
    provider: "deepseek",
    model: "deepseek-v3",
    capabilities: ["coding", "analysis", "creative_writing", "summarization", "data_extraction", "translation", "research", "math_reasoning"],
    contextWindow: 128000,
    costPer1kInput: 0.027,
    costPer1kOutput: 0.11,
    tier: "budget",
  },
  // Mistral
  {
    provider: "mistral",
    model: "mistral-large-latest",
    capabilities: ["coding", "analysis", "creative_writing", "math_reasoning", "summarization", "data_extraction", "translation", "research"],
    contextWindow: 128000,
    costPer1kInput: 0.2,
    costPer1kOutput: 0.6,
    tier: "standard",
  },
  {
    provider: "mistral",
    model: "codestral-latest",
    capabilities: ["coding", "data_extraction"],
    contextWindow: 256000,
    costPer1kInput: 0.08,
    costPer1kOutput: 0.24,
    tier: "budget",
  },
  // Groq (ultra-fast inference)
  {
    provider: "groq",
    model: "llama-3.3-70b-versatile",
    capabilities: ["coding", "analysis", "creative_writing", "summarization", "data_extraction", "translation", "math_reasoning"],
    contextWindow: 128000,
    costPer1kInput: 0.059,
    costPer1kOutput: 0.079,
    tier: "budget",
  },
  {
    provider: "groq",
    model: "deepseek-r1-distill-llama-70b",
    capabilities: ["coding", "analysis", "math_reasoning"],
    contextWindow: 128000,
    costPer1kInput: 0.075,
    costPer1kOutput: 0.09,
    tier: "budget",
  },
  // Together AI (open-source models)
  {
    provider: "together",
    model: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
    capabilities: ["coding", "analysis", "creative_writing", "summarization", "data_extraction", "translation", "math_reasoning"],
    contextWindow: 128000,
    costPer1kInput: 0.088,
    costPer1kOutput: 0.088,
    tier: "budget",
  },
  {
    provider: "together",
    model: "deepseek-ai/DeepSeek-R1",
    capabilities: ["coding", "analysis", "math_reasoning"],
    contextWindow: 128000,
    costPer1kInput: 0.17,
    costPer1kOutput: 0.43,
    tier: "budget",
  },
  // Cohere
  {
    provider: "cohere",
    model: "command-r-plus",
    capabilities: ["coding", "analysis", "creative_writing", "summarization", "data_extraction", "translation", "research"],
    contextWindow: 128000,
    costPer1kInput: 0.25,
    costPer1kOutput: 1.0,
    tier: "standard",
  },
  {
    provider: "cohere",
    model: "command-r",
    capabilities: ["coding", "analysis", "summarization", "data_extraction", "translation"],
    contextWindow: 128000,
    costPer1kInput: 0.015,
    costPer1kOutput: 0.06,
    tier: "budget",
  },
];
